config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @average_cubic_weight = @items.average(:cubic_weight)
    if params[:category]
      @items = @items.where(category: params["category"])
      @average_cubic_weight = @items.average(:cubic_weight)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper

end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :item_category %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :item_title %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.text_field :width, id: :item_width %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.text_field :length, id: :item_length %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height, id: :item_height %>
  </div>

  <div class="field">
    <%= form.label :cubic_weight %>
    <%= form.text_field :cubic_weight, id: :item_cubic_weight %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_heading.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <div class="container">
    <div class="center">
      <a href="/"><img alt="Brand" src="//static.kogan.com/static/img/kogan-logo.eac8023e4ee1.png"></a>
      <h2>The easiest way to find the Average Cubic Weight (kg) per category</h2>
    </div>
  </div>
</div>

<div class="container filter">
  <div class="center">
    <div class="filter">
      <div class="form-group">
        <%= form_tag items_path, method: :get do %>
          <%= label_tag "Search Category" %>
          <%= select_tag("category", options_from_collection_for_select(@items.all.to_a.uniq{ |o| o.category}, :category, :category, params[:category]),
                        { include_blank: true, class: 'form-control' }) %>
          <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="center">
    <h3 class="cubic-weight">Average Cubic Weight: <%= number_with_precision(@average_cubic_weight, precision: 2) %> kg</h3>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'heading' %>

<div class="container">
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Width</th>
      <th>Length</th>
      <th>Height</th>
      <th>Cubic Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.category %></td>
        <td><%= item.title %></td>
        <% if item.width %>
          <td><%= number_with_precision(item.width, precision: 1) %> cm</td>
        <% else %>
          <td>n/a</td>
        <% end %>
        <% if item.length %>
          <td><%= number_with_precision(item.length, precision: 1) %> cm</td>
        <% else %>
          <td>n/a</td>
        <% end %>
        <% if item.height %>
          <td><%= number_with_precision(item.height, precision: 1) %> cm</td>
        <% else %>
          <td>n/a</td>
        <% end %>
        <% if item.cubic_weight %>
          <td><%= number_with_precision(item.cubic_weight, precision: 2) %> kg</td>
        <% else %>
          <td>n/a</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Width:</strong>
  <%= @item.width %>
</p>

<p>
  <strong>Length:</strong>
  <%= @item.length %>
</p>

<p>
  <strong>Height:</strong>
  <%= @item.height %>
</p>

<p>
  <strong>Cubic weight:</strong>
  <%= @item.cubic_weight %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KoganChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>